version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:10
    steps:
      - checkout
      - run:
          name: "NPM Install bits"
          command: "npm install"

workflows:
  build-and-test:
    jobs:
      - build-and-test
