version: 2.1

orbs: 
    node: circleci/node@5.0.2
    browser-tools: circleci/browser-tools@1.2.5

jobs:
  build-and-test-nodev8:
    executor:
      name: node/default
      tag: '8.17.0'
    steps:
      - save_cache:
          key: node-cache
          paths:
            - node_modules
      - checkout
      - browser-tools/install-browser-tools:
          chrome-version: latest      
      - node/install-packages:
            override-ci-command: npm install
      - run:
          command: npm run test
  build-and-test-nodev10:
    executor:
      name: node/default
      tag: '10.24.1'
    steps:
      - save_cache:
          key: node-cache
          paths:
            - node_modules
      - checkout
      - browser-tools/install-browser-tools:
          chrome-version: latest      
      - node/install-packages:
            override-ci-command: npm install
      - run:
          command: npm run test


workflows:
  build-and-test:
    jobs:
      - build-and-test-nodev8
      - build-and-test-nodev10
#      - node/test:
#          test-results-for: mocha
#          requires:
#            - build-and-test
