version: 2.1

orbs: 
    node: circleci/node@5.0.2

jobs:
  build-and-test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages:
            override-ci-command: npm install
#      - run:
#          name: "NPM Install bits"
#          command: "npm install"
#      - run:
#          name: "Node make deps"
#          command: "node make all"
#      - run:
#          name: "NPM test"
#          command: "npm test"

workflows:
  build-and-test:
    jobs:
      - build-and-test
      - node/test:
          test-results-for: mocha
          requires:
            - build-and-test
