version: 2.1

orbs: 
    node: circleci/node@5.0.2
    browser-tools: circleci/browser-tools@1.2.5

jobs:
  build-and-test:
    docker:
      - image: cimg/node:lts
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - browser-tools/install-browser-tools:
          chrome-version: latest      
      - node/install-packages:
            override-ci-command: npm install
      - run:
          command: npm run test
#      - run:
#          name: "NPM Install bits"
#          command: "npm install"
#      - run:
#          name: "Node make deps"
#          command: "node make all"
#      - run:
#          name: "NPM test"
#          command: "npm test"

workflows:
  build-and-test:
    jobs:
      - build-and-test
#      - node/test:
#          test-results-for: mocha
#          requires:
#            - build-and-test
