version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:10.24.1
    steps:
      - checkout
      - run:
          name: "NPM Install bits"
          command: "npm install"
      - run:
          name: "NPM test"
          command: "npm test"

workflows:
  build-and-test:
    jobs:
      - build-and-test
